pipeline:
  tests:
    image: node:alpine
    commands:
      - npm
      - npm test
    when:
      event: [push, tag]

  publish-staging:
    image: plugins/docker
    repo: nossas/bonde-graphql
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH}
    when:
      status: success
      branch: [hotfix-*, release-*, feature-*, develop]

  deploy-staging-api-v2:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: staging/api-v2
    group: concurrent
    docker_image: nossas/bonde-graphql:${DRONE_BRANCH}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix-*, release-*, feature-*, develop]

  deploy-staging-api-services:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: staging/api-services
    group: concurrent
    docker_image: nossas/bonde-graphql:${DRONE_BRANCH}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix-*, release-*, feature-*, develop]

  publish-production:
    image: plugins/docker
    repo: nossas/bonde-graphql
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG##v}
    when:
      status: success
      event: tag

  deploy-production-api-v2:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: staging/api-services
    group: concurrent
    docker_image: nossas/bonde-graphql:${DRONE_TAG##v}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      event: tag

  deploy-production-api-services:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: staging/api-services
    group: concurrent
    docker_image: nossas/bonde-graphql:${DRONE_TAG##v}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      event: tag

  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: bonde_bots
    username: CI - ${DRONE_REPO_NAME}
    when:
      event: [ push, tag, build, publish, deployment, pull_request ]
      status: [ success, failure ]
